-- Run this in your Supabase SQL Editor to set up the tables

-- 1. Batches Table
create table batches (
  id bigint generated by default as identity primary key,
  batch_id text unique not null,
  medicine_name text not null,
  manufacturer text not null,
  expiry_date date not null,
  purity float default 100.0,
  is_recalled boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Scan Logs Table
create table scan_logs (
  id bigint generated by default as identity primary key,
  batch_id text,
  status text, -- VALID, FAKE, EXPIRED, RECALLED
  scanned_by text,
  timestamp timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Enable Row Level Security (Optional but recommended)
alter table batches enable row level security;
alter table scan_logs enable row level security;

-- 4. Policies (Allow public read/write for Hackathon demo)
create policy "Public Batches Read" on batches for select using (true);
create policy "Public Batches Insert" on batches for insert with check (true);
create policy "Public Logs Read" on scan_logs for select using (true);
create policy "Public Logs Insert" on scan_logs for insert with check (true);

-- 5. Seed Data
insert into batches (batch_id, medicine_name, manufacturer, expiry_date, purity, is_recalled) values
('MED-2025-001', 'Paracetamol 500mg', 'HealthCorp', '2026-12-31', 99.9, false),
('MED-002', 'Amoxicillin 250mg', 'BioTech', '2025-06-30', 98.5, false),
('BAD-001', 'Fake Pills', 'Unknown', '2024-01-01', 50.0, true);
